/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nick Slough (https://sketchfab.com/BeholderDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vendels-workshop-e1594640fe8f44569d0e5824f1074eb9
Title: Vendel's Workshop
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import roomScene from "../assets/3d/vendels_workshop.glb";

export function Room({
  isRotating,
  setIsRotating,
  setCurrentStage,
  currentFocusPoint,
  ...props
}) {
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(roomScene);
  const roomRef = useRef();

  // Use a ref for the last mouse x position
  const lastX = useRef(0);
  // Use a ref for rotation speed
  const rotationSpeed = useRef(0);
  // Define a damping factor to control rotation damping
  const dampingFactor = 0.95;

  // Handle pointer (mouse or touch) down event
  const handlePointerDown = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(true);

    // Calculate the clientX based on whether it's a touch event or a mouse event
    const clientX = event.touches ? event.touches[0].clientX : event.clientX;

    // Store the current clientX position for reference
    lastX.current = clientX;
  };

  // Handle pointer (mouse or touch) up event
  const handlePointerUp = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(false);
  };

  // Handle pointer (mouse or touch) move event
  const handlePointerMove = (event) => {
    event.stopPropagation();
    event.preventDefault();
    if (isRotating) {
      // If rotation is enabled, calculate the change in clientX position
      const clientX = event.touches ? event.touches[0].clientX : event.clientX;

      // calculate the change in the horizontal position of the mouse cursor or touch input,
      // relative to the viewport's width
      const delta = (clientX - lastX.current) / viewport.width;

      // Update the island's rotation based on the mouse/touch movement
      roomRef.current.rotation.y += delta * 0.01 * Math.PI;

      // Update the reference for the last clientX position
      lastX.current = clientX;

      // Update the rotation speed
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  // Handle keydown events
  const handleKeyDown = (event) => {
    if (event.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);

      roomRef.current.rotation.y += 0.005 * Math.PI;
      rotationSpeed.current = 0.007;
    } else if (event.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);

      roomRef.current.rotation.y -= 0.005 * Math.PI;
      rotationSpeed.current = -0.007;
    }
  };

  // Handle keyup events
  const handleKeyUp = (event) => {
    if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  // Touch events for mobile devices
  const handleTouchStart = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  };

  const handleTouchEnd = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  const handleTouchMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;

      roomRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    canvas.addEventListener("touchstart", handleTouchStart);
    canvas.addEventListener("touchend", handleTouchEnd);
    canvas.addEventListener("touchmove", handleTouchMove);

    // Remove event listeners when component unmounts
    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
      canvas.removeEventListener("touchstart", handleTouchStart);
      canvas.removeEventListener("touchend", handleTouchEnd);
      canvas.removeEventListener("touchmove", handleTouchMove);
    };
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

  // This function is called on each frame update
  useFrame(() => {
    // If not rotating, apply damping to slow down the rotation (smoothly)
    if (!isRotating) {
      // Apply damping factor
      rotationSpeed.current *= dampingFactor;

      // Stop rotation when speed is very small
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      roomRef.current.rotation.y += rotationSpeed.current;
    } else {
      // When rotating, determine the current stage based on island's orientation
      const rotation = roomRef.current.rotation.y;

      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  });

  return (
    <a.group ref={roomRef} {...props}>
      <a.group>
        {/* <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials.PaletteMaterial001}
        /> */}
        <mesh geometry={nodes.Object_2.geometry} material={materials.mat5} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.mat8} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.mat1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.mat10} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.mat11} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.mat12} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.mat13} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.mat14} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.mat15} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.mat16} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.mat16} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.mat2} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.mat17} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.mat17} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.mat17} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.mat18} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.mat18} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.mat19} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.mat20} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.mat20} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.mat21} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.mat21} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.mat22} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.mat22} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.mat23} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.mat24} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.mat24} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.mat4} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.mat7} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.mat9} />
      </a.group>
    </a.group>
  );
}

// useGLTF.preload("/vendels_workshop.glb");

// export default Room;
